import type { TechStackT } from './tech-stack-types';

export const techStack: TechStackT = {
  AI: [
    'Python',
    'R',
    'JavaScript',
    'TensorFlow',
    'PyTorch',
    'Keras',
    'Scikit-learn',
    'OpenCV',
    'NLTK',
    'SpaCy',
    'Pandas',
    'NumPy',
    'Apache Spark',
  ],
  Mobile: ['Swift', 'Objective-C', 'Flutter', 'React Native', 'Kotlin', 'Java'],
  'Back-End': [
    'Node.js',
    'C#',
    'C/C++',
    'Java',
    'Python',
    'Go',
    'Ruby',
    'Rust',
    'Solidity',
    'PHP',
  ],
  'Front-End': [
    'JavaScript/TypeScript',
    'Swift/Objective C',
    'Kotlin',
    'SCSS/SASS',
    'HTML/CSS',
  ],
  Cloud: [
    'AWS',
    'AWS Lambda',
    'GCP',
    'MS Azure',
    'Azure Functions',
    'DigitalOcean',
    'GC Functions',
  ],
  Design: [
    'Figma',
    'Photoshop',
    'Illustrator',
    'InVision',
    'Sketch',
    'Zeplin',
    'Adobe XD',
  ],
  'Continuous Integration': [
    'Jenkins',
    'GitHub',
    'GitLab',
    'BitBucket',
    'Code Build',
    'Fastline',
    'Code Commit',
    'Bitrise',
    'TeamCity',
    'Terraform',
  ],
};
